service: ${file(./config/service_name.yml):service}
provider:
  name: aws
  runtime: dotnetcore1.0
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    SLS_DEBUG: "*"
    PROVIDER: 'aws'

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
   
package:
  artifact: bin/release/netcoreapp1.0/deploy-package.zip
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
    - 'config/**'
    - 'node_modules/**'