service: ${file(./config/service_name.yml):service}
provider:
  name: aws
  runtime: dotnetcore1.0
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    SLS_DEBUG: "*"
    PROVIDER: 'aws'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
functions:
  proxyRequest:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events:
      - http:
            path: /         
            method: post                                      
            cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent 
package:
  artifact: bin/release/netcoreapp1.0/deploy-package.zip
  exclude: 
    - 'test/**'
    - 'coverage/**'
    - 'LICENSE'
    - 'README.md'
    - '.travis.yml'
    - 'docs/**'
    - 'config/**'